version: '3.9'
services:
  express:
    build:
      context: ./
    ports:
      - '3000:3000'
      - '9229:9229'
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
    command: /bin/sh -c "npm install && npm run start"
    environment:
      - SERVER_HOST=${SERVER_HOST}
      - SERVER_PORT=${SERVER_PORT}
volumes:
  node_modules: