version: '3.9'
services:
  express:
    build:
      context: ./
    ports:
      - '3000:3000'
      - '9229:9229'
    volumes:
      - ./node_modules:/app/node_modules
      - ./:/app
    command: npm run start
    environment:
      - SERVER_HOST=${SERVER_HOST}
      - SERVER_PORT=${SERVER_PORT}